### PR TITLE
Don't use public API in get_private

### PR DESCRIPTION
**Pull request by matklad**
Just a bug fix

### CODE REVIEW

**Review by ozkriff — DISMISSED** [review]

**Review by stanislav-tkach — DISMISSED** [review]

**Review by slowli — DISMISSED** [review]
LGTM. Ideally, there should be tests calling `get_private`, but I suppose they could be added (a little) later.

**Comment by slowli** [comment]
May I suggest the following patch to test this change?

```patch
    Move `get_wallets` endpoint to private API
    
    ...in order to test `get_private` method in `TestKitApi`

diff --git a/tests/currency/cryptocurrency.rs b/tests/currency/cryptocurrency.rs
index ada2057..fd442e6 100644
--- a/tests/currency/cryptocurrency.rs
+++ b/tests/currency/cryptocurrency.rs
@@ -258,6 +258,12 @@ impl CryptocurrencyApi {
     fn get_wallets(&self, _: &mut Request) -> IronResult<Response> {
         self.ok_response(&serde_json::to_value(&self.wallets()).unwrap())
     }
+
+    fn wire_private(&self, router: &mut Router) {
+        let self_ = self.clone();
+        let get_wallets = move |req: &mut Request| self_.get_wallets(req);
+        router.get("/v1/wallets", get_wallets, "get_wallets");
+    }
 }
 
 impl Api for CryptocurrencyApi {
@@ -265,8 +271,6 @@ impl Api for CryptocurrencyApi {
         let self_ = self.clone();
         let post_transaction = move |req: &mut Request| self_.post_transaction(req);
         let self_ = self.clone();
-        let get_wallets = move |req: &mut Request| self_.get_wallets(req);
-        let self_ = self.clone();
         let get_wallet = move |req: &mut Request| self_.get_wallet(req);
 
         // Bind the transaction handler to a specific route.
@@ -275,7 +279,6 @@ impl Api for CryptocurrencyApi {
             post_transaction,
             "post_transaction",
         );
-        router.get("/v1/wallets", get_wallets, "get_wallets");
         router.get("/v1/wallet/:pub_key", get_wallet, "get_wallet");
     }
 }
@@ -323,4 +326,14 @@ impl Service for CurrencyService {
         api.wire(&mut router);
         Some(Box::new(router))
     }
+
+    fn private_api_handler(&self, ctx: &ApiContext) -> Option<Box<Handler>> {
+        let mut router = Router::new();
+        let api = CryptocurrencyApi {
+            channel: ctx.node_channel().clone(),
+            blockchain: ctx.blockchain().clone(),
+        };
+        api.wire_private(&mut router);
+        Some(Box::new(router))
+    }
 }
diff --git a/tests/currency/main.rs b/tests/currency/main.rs
index 60b8e96..464cd76 100644
--- a/tests/currency/main.rs
+++ b/tests/currency/main.rs
@@ -74,7 +74,7 @@ fn get_wallet(api: &TestKitApi, pubkey: &PublicKey) -> Wallet {
 }
 
 fn get_all_wallets(api: &TestKitApi) -> Vec<Wallet> {
-    api.get(ApiKind::Service("cryptocurrency"), "v1/wallets")
+    api.get_private(ApiKind::Service("cryptocurrency"), "v1/wallets")
 }
 
 #[test] 
```

It moves the endpoint dumping all wallets in the cryptocurrency service from public to private API, which seems like a sensible change to me.

**Comment by matklad** [comment]
@slowli sounds like a good idea in theory, but I am not sure that it makes sense to create divergence between http://github.com/exonum/cryptocurrency and the currency in this repository. I would say that probably we should move currency tests from this repository to exonum/cryptocurrency instead. 

Let's add a dummy private get endpoint to the counter example instead perhaps? 

Yeah, originally I need this change to write some tests for exonum-bundle, but it uses non-latest version of testkit anyway...

**Comment by slowli** [comment]
If anything, I'd say that moving `get_wallets` to a private endpoint makes the cryptocurrency service closer to real life. Without pagination, maintaining this endpoint as public is unsustainable; the private endpoint would correspond to "dump database" option in RDBMSs (which is available to admins, generally).

**Comment by matklad** [comment]
>If anything, I'd say that moving get_wallets to a private endpoint makes the cryptocurrency service closer to real life.

Totally agree here! That means that we probably need to update http://github.com/exonum/cryptocurrency as well. The thing that worries me is that the code in that repository, and in the currency test here is *almost* the same, so I am somewhat hesitant to touch either of them.

Hm, looks like there **are** testkit tests in cryptocurrencty repository: https://github.com/exonum/cryptocurrency/blob/master/tests/api.rs. Do we need to duplicate them here?

How about this plan:

* Merge this PR (it now has a selftest for the `counter` example)
* Delete `tests/currency` folder and instead point to https://github.com/exonum/cryptocurrency/blob/master/tests/api.rs in the readme
* Make get_wallets private and add tests in the cryptocurrency repository (this will require a new release of testkit, or a [replace] in Cargo.toml)

**Comment by slowli** [comment]
Sounds awesome!

- Code duplication is not needed indeed. The `tests/currency` tests where written during the crate inception, so there were no tests in the `cryptocurrency` repo (and there is currently no way to export the demo service, since it's not a crate; see exonum/cryptocurrency#46).
- I'm for a release (сс @alekseysidorov; v0.1.2 seems to fit by semver semantics) after merging this PR (and possibly miscellaneous ones such as #22 and #14), since the bug fixed in this PR complicates the use of the testkit for practical purposes.

**Review by stanislav-tkach — DISMISSED** [review]

**Review by alekseysidorov — DISMISSED** [review]

**Comment by alekseysidorov** [comment]
Please add entry in the CHANGELOG.md file.

**Comment by matklad** [comment]
Not sure what's up with CI: looks like some problems with external dependencies.

**Review by alekseysidorov — APPROVED** [review]

**Pull request merged**
