### PR TITLE
Use conventional layout for multi-module tests

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
Oups, pushed accidentally uncommitted tests :)

**Comment by matklad** [comment]
To expand a bit on what happens here, Cargo recently gained out-of-the box support for multimodule binaries, examples and tests.

If before one could write `src/bin/foo.rs`, `src/examples/bar.rs` and `src/tests/quux.rs`, now it is possible to use `src/bin/foo/main.rs`, `src/examples/bar/main.rs` and `src/tests/quux/main.rs` and use `mod spam;` in `main.rs` files.

**Review by stanislav-tkach — DISMISSED** [review]

**Review by slowli — COMMENTED** [review]
I suppose this provides a definitive answer for my question about multi-file examples in #18 😃 Mostly good as of fab22d487be5c70e2858f57b69a41d1885f8ae72, with a couple of comments:

- Could you add the copyright notice at the beginning of each new file?
- In the future, please create PR branches in your own fork of the repo, rather than in the `exonum`-owned repo.

**Comment by matklad** [comment]
>Could you add the copyright notice at the beginning of each new file?

Done! I could add something like https://github.com/intellij-rust/intellij-rust/blob/master/check-license.sh to the CI script to have this checked automatically. 

>In the future, please create PR branches in your own fork of the repo, rather than in the exonum-owned repo.

Sure! I've actually created a repository with two remotes, `origing` and `fork`, locally, and correctly pushed the branch to `fork`, but I've messed up the actual remote url =/ 🤷‍♀️

**Review by stanislav-tkach — DISMISSED** [review]

**Review by aleksuss — APPROVED** [review]

**Review by alekseysidorov — APPROVED** [review]

**Review by stanislav-tkach — APPROVED** [review]

**Pull request merged**
